stages:
  - lint
  - build
  - package
  - install
#   - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
  DEBIAN_FRONTEND: noninteractive

before_script:
  - apt-get update -qq
  - apt-get install -y git
  - git submodule update --init --recursive

lint:cppcheck:
  stage: lint
  image: ubuntu:22.04
  script:
    - apt-get install -y cppcheck libopenmpi-dev libhdf5-dev libhdf5-openmpi-dev libssl-dev nlohmann-json3-dev
    - cppcheck --std=c++17 --language=c++ --error-exitcode=1 --enable=all --suppress=unmatchedSuppression --suppress=missingIncludeSystem --suppress=unusedFunction src/*.cpp src/PLIHDF5/*

lint:clang-format:
  stage: lint
  image: ubuntu:22.04
  script:
    - apt-get install -y clang-format
    - clang-format --style=Google -i src/*.cpp src/PLIHDF5/*

lint:clang-tidy:
  stage: lint
  image: ubuntu:22.04
  script:
    - apt-get install -y clang-tidy cmake libopenmpi-dev libhdf5-dev libhdf5-openmpi-dev libssl-dev g++ gcc nlohmann-json3-dev
    - mkdir build
    - cd build
    - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
    - clang-tidy -p=. ../src/*.cpp ../src/PLIHDF5/*

lint:cpplint:
  stage: lint
  image: ubuntu:22.04
  script:
    - apt-get install -y cpplint
    - cpplint src/*.cpp src/PLIHDF5/*

build:ubuntu:
  stage: build
  image: ubuntu:22.04
  script:
    - apt-get install -y cmake make gcc g++ libopenmpi-dev libhdf5-dev libhdf5-openmpi-dev libssl-dev nlohmann-json3-dev
    - mkdir build
    - cd build
    - cmake -DPLIHDF5_USE_LINTING=OFF ..
    - make

package:ubuntu22.04:
  stage: package
  image: ubuntu:22.04
  script:
    - apt-get install -y cmake make gcc g++ libopenmpi-dev libhdf5-dev libhdf5-openmpi-dev libssl-dev nlohmann-json3-dev dpkg-dev lsb-release
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTING=OFF -DPLIHDF5_USE_LINTING=OFF ..
    - make
    - cpack
  artifacts:
    paths:
      - build/plihdf5_1.0.1_amd64-devel.deb
      - build/plihdf5_1.0.1_amd64-runtime.deb

package:ubuntu20.04:
  stage: package
  image: ubuntu:20.04
  script:
    - apt-get install -y cmake make gcc g++ libopenmpi-dev libhdf5-dev libhdf5-openmpi-dev libssl-dev nlohmann-json3-dev dpkg-dev lsb-release 
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTING=OFF -DPLIHDF5_USE_LINTING=OFF ..
    - make
    - cpack
  artifacts:
    paths:
      - build/plihdf5_1.0.1_amd64-devel.deb
      - build/plihdf5_1.0.1_amd64-runtime.deb

install:ubuntu20.04:
  stage: install
  image: ubuntu:20.04
  dependencies:
    - package:ubuntu20.04
  script:
    - apt-get update -qq
    - apt-get install -y ./build/plihdf5_1.0.1_amd64-devel.deb ./build/plihdf5_1.0.1_amd64-runtime.deb

install:ubuntu22.04:
  stage: install
  image: ubuntu:22.04
  dependencies:
    - package:ubuntu22.04
  script:
    - apt-get update -qq
    - apt-get install -y ./build/plihdf5_1.0.1_amd64-devel.deb ./build/plihdf5_1.0.1_amd64-runtime.deb
# test:ubuntu:
#   stage: test
#   image: ubuntu:22.04
#   script:
#     - apt-get install -y cmake make gcc g++ libopenmpi-dev libhdf5-dev libhdf5-openmpi-dev libssl-dev
#     - cd build
#     - make test
#   dependencies:
#     - build:ubuntu
