fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=Google, -i]
      - id: clang-tidy
        args: [-p=build]
      - id: cppcheck
        args: [--std=c++17, --language=c++]
      - id: cpplint
