find_program(LSB_RELEASE_EXEC lsb_release)

# ##############################################################################
# Create packages
# ##############################################################################
if(LSB_RELEASE_EXEC)
  # Get the OS release
  execute_process(
    COMMAND ${LSB_RELEASE_EXEC} -is
    OUTPUT_VARIABLE LSB_RELEASE_ID_SHORT
    OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(
    COMMAND ${LSB_RELEASE_EXEC} -rs
    OUTPUT_VARIABLE LSB_RELEASE_NUMBER
    OUTPUT_STRIP_TRAILING_WHITESPACE)
  message(
    STATUS "Build platform : ${LSB_RELEASE_ID_SHORT}-${LSB_RELEASE_NUMBER}")

  # Get the system architecture
  execute_process(
    COMMAND uname -m
    COMMAND tr -d '\n'
    OUTPUT_VARIABLE ARCHITECTURE)
  # Convert x86_64 to amd64
  if(${ARCHITECTURE} STREQUAL "x86_64")
    set(ARCHITECTURE amd64)
  endif()
  message(STATUS "Build architecture : ${ARCHITECTURE}")
endif(LSB_RELEASE_EXEC)

include(InstallRequiredSystemLibraries)
set(CPACK_PACKAGE_VERSION_MAJOR ${CMAKE_PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${CMAKE_PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${CMAKE_PROJECT_VERSION_PATCH})
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")

set(OS_NAME "")
set(CPACK_DEB_COMPONENT_INSTALL ON)
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION}")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "${ARCHITECTURE}")
set(CPACK_DEBIAN_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Jan Reuter & Felix Matuschke")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "3D PLI HDF5")
set(CPACK_DEBIAN_RUNTIME_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_DEBIAN_DEVEL_PACKAGE_DEPENDS "${PROJECT_NAME}")
set(CPACK_DEBIAN_DEVEL_PACKAGE_NAME "${PROJECT_NAME}-dev")
set(CPACK_STGZ_COMPRESSION "gzip")
set(CPACK_STGZ_COMPRESSION_LEVEL 9)
set(CPACK_STGZ_COMPRESSION_METHOD "DEFLATE")
set(CPACK_STGZ_COMPRESSION_TYPE "tar")
set(CPACK_STGZ_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_STGZ_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION}")
set(CPACK_STGZ_PACKAGE_ARCHITECTURE "${ARCHITECTURE}")
set(CPACK_STGZ_PACKAGE_MAINTAINER "Jan Reuter & Felix Matuschke")
set(CPACK_STGZ_PACKAGE_DESCRIPTION "3D PLI HDF5")
set(CPACK_STGZ_DEVEL_PACKAGE_DEPENDS "${PROJECT_NAME}")
set(CPACK_STGZ_DEVEL_PACKAGE_NAME "${PROJECT_NAME}-dev")
set(CPACK_STGZ_RUNTIME_PACKAGE_NAME "${PROJECT_NAME}")
